apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boardwalk.fullname" . }}-frontend
  labels:
    {{- include "boardwalk.labels" . | nindent 4 }}
    {{- include "boardwalk.frontendSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "boardwalk.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boardwalk.frontendSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (printf "%s-sa" (include "boardwalk.fullname" .)) }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
