{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-sa" (include "boardwalk.fullname" .)) }}
  labels:
    {{- include "boardwalk.labels" . | nindent 4 }}
{{- end }}
